
#ifndef __AQUA__STD_MACROS_H
	#define __AQUA__STD_MACROS_H
	
	#define SURFACE_VERTEX_COUNT 4
	#define PATH ""
	
	#define _UI64_MAX 0xFFFFFFFFFFFFFFFF
	#define _SI64_MAX 0xFFFFFFFFFFFFFFFF / 2
	
	#define _UI64_MAX_MARGIN (_UI64_MAX >> 8)
	#define _SI64_MAX_MARGIN (_SI64_MAX >> 8)
	
	#define MAX_EVENTS_IN_EVENT_LIST 256
	
	// socket stuff
	
	#define SOCKET_AF_INET 1
	#define SOCKET_SOCK_STREAM 2
	
	#define SOCKET_IP_LOCALHOST 0
	#define SOCKET_IP_INTERNAL 1
	#define SOCKET_IP_EXTERNAL 2
	
	#define SOCKET_CLIENT 0
	#define SOCKET_SERVER 1
	#define SOCKET_MIXED 2
	
	#define SOCKET_REUSE_ADDRESS ((void*) 0)
	#define SOCKET_REUSE_PORT -1
	
	#define SOCKET_DEFAULT_BUFFER_SIZE 1024
	
	// misc stuff
	
	#define HORIZONTAL 0
	#define VERTICAL 1
	
	#define UP 2
	#define DOWN 3
	#define LEFT 4
	#define RIGHT 5
	#define CENTER 6
	
	#define HIDDEN 0
	#define VISIBLE 1
	
	// server port definitions
	
	#define PORT_SERVER_AQUA 0
	#define PORT_SERVER_COMPILER 1
	#define PORT_SERVER_AQUA_STORE_UPLOAD 2
	#define PORT_SERVER_AQUA_STORE 3
	
	// platforms
	
	#define PLATFORM_64BIT 0b1
	#define PLATFORM_UNIX 0b10
	#define PLATFORM_WINDOWS 0b100
	#define PLATFORM_CANCER 0b1000
	#define PLATFORM_MOBILE 0b10000
	#define PLATFORM_CUSTOM 0b100000
	#define PLATFORM_KNOWN 0b1000000
	
	#define PLATFORM_OTHER PLATFORM_64BIT
	#define PLATFORM_LINUX PLATFORM_KNOWN | PLATFORM_64BIT | PLATFORM_UNIX
	#define PLATFORM_WIN64 PLATFORM_KNOWN | PLATFORM_64BIT | PLATFORM_WINDOWS
	#define PLATFORM_WIN32 PLATFORM_KNOWN | PLATFORM_WINDOWS
	#define PLATFORM_MACOS PLATFORM_KNOWN | PLATFORM_64BIT | PLATFORM_UNIX | PLATFORM_CANCER
	#define PLATFORM_IOS PLATFORM_KNOWN | PLATFORM_64BIT | PLATFORM_UNIX | PLATFORM_CANCER | PLATFORM_MOBILE
	#define PLATFORM_ANDROID PLATFORM_KNOWN | PLATFORM_64BIT | PLATFORM_UNIX | PLATFORM_MOBILE
	#define PLATFORM_AQUA PLATFORM_KNOWN | PLATFORM_CUSTOM
	
	// predefined textures
	
	#define TEXTURE_BACKGROUND 0
	#define TEXTURE_FROSTED_BACKGROUND 1
	
#endif
