
// flags

#define KOS_GL_API_OPENGL   0b00001
#define KOS_GL_API_EMBEDDED 0b00010

#define KOS_CONTEXT_SDL2    0b00100
#define KOS_CONTEXT_JNI     0b01000
#define KOS_CONTEXT_BCM     0b10000

// platform definitions

#define KOS_DESKTOP (KOS_CONTEXT_SDL2 | KOS_GL_API_OPENGL)
#define KOS_TESTING (KOS_CONTEXT_BCM  | KOS_GL_API_OPENGL)
#define KOS_RPI     (KOS_CONTEXT_BCM  | KOS_GL_API_OPENGL | KOS_GL_API_EMBEDDED)
#define KOS_ANDROID (KOS_CONTEXT_JNI  | KOS_GL_API_OPENGL | KOS_GL_API_EMBEDDED)

/// THIS PART IS IMPORTANT

#ifndef KOS_CURRENT
	#define KOS_CURRENT KOS_ANDROID // KOS_TESTING
#endif

// platform facilities

#define KOS_USES_SDL2 (KOS_CURRENT & KOS_CONTEXT_SDL2)
#define KOS_USES_BCM  (KOS_CURRENT & KOS_CONTEXT_BCM)
#define KOS_USES_JNI  (KOS_CURRENT & KOS_CONTEXT_JNI)

#define KOS_USES_SHADER_PIPELINE KOS_USES_JNI

#define KOS_USES_OPENGL         (KOS_CURRENT                      & KOS_GL_API_OPENGL)
#define KOS_USES_OPENGLES       (KOS_USES_OPENGL &&   KOS_CURRENT & KOS_GL_API_EMBEDDED)
#define KOS_USES_OPENGL_DESKTOP (KOS_USES_OPENGL && !(KOS_CURRENT & KOS_GL_API_EMBEDDED))

// glue.h inclusion

#include "glue.h"
