
#ifndef __AQUA__KOS_MACROS_AND_INCLUSIONS_PREDEFINED_TEXTURES_H
	#define __AQUA__KOS_MACROS_AND_INCLUSIONS_PREDEFINED_TEXTURES_H
	
	#define TEXTURE_BACKGROUND         0
	#define TEXTURE_FROSTED_BACKGROUND 1
	
#endif
